CREATE PROCEDURE [dbo].[sp_Reset_BrandId]
AS
BEGIN
	SET NOCOUNT ON;
	IF EXISTS( SELECT 1 FROM Brands)
BEGIN
	DECLARE @newId AS INT = (SELECT TOP 1 Id FROM Brands ORDER BY Id DESC)
	DBCC CHECKIDENT('Brands', RESEED, @newId);
END
ELSE
BEGIN
	DBCC CHECKIDENT('Brands', RESEED, 0);
END
   
END
